[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "coverage==7.6.5",
    "llm==0.17.1",
    "pytest-cov==6.0.0",
    "pytest==8.3.3",
    "ruff==0.7.3",
]
